name: Verificar Mensaje de Commit

on:
  pull_request:
    types:
      - opened

jobs:
  verificar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar Mensaje de Commit
        uses: actions/checkout@v2
        
      - name: Obtener Mensaje de Commit
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})"
        
      - name: Comprobar Formato de Inicio de Commit
        run: |
          commit_message="${{ steps.commit_message.outputs.message }}"
          if [[ ! $commit_message =~ ^\[FORMATO_DE_INICIO\] ]]; then
            echo "El mensaje de commit no cumple con el formato de inicio requerido."  # Este es un comentario de ejemplo
            exit 1
          fi
