name: Verificar Mensaje de Commit

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  verificar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar Formato de Inicio de Commit
        run: |          
          echo "Elrequerido."
          exit 1
          
