name: Verificar Regla de Protección de Rama

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  verificar-regla:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar Mensaje de Commit
        uses: actions/checkout@v2
        
      - name: Comprobar Formato de Inicio de Commit
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          if [[ $commit_message != "[FORMATO_DE_INICIO]*" ]]; then
            echo "El mensaje de commit no cumple con el formato de inicio requerido, pero se permitirá el merge."
          else
            echo "El mensaje de commit cumple con el formato de inicio requerido."
          fi
